import {ProcessingState, User} from '../models';

const users: User[] = [
    { name: 'Sam', age: 30, favoriteColor: 'blue' },
    { name: 'Alice', age: 25, favoriteColor: 'green' },
    { name: 'Bob', age: 40, favoriteColor: 'red' },
    { name: 'Carol', age: 29, favoriteColor: 'orange' },
    { name: 'Dave', age: 34, favoriteColor: 'blue' },
    { name: 'Eve', age: 22, favoriteColor: 'green' },
    { name: 'Frank', age: 31, favoriteColor: 'red' },
    { name: 'Grace', age: 28, favoriteColor: 'orange' },
    { name: 'Heidi', age: 26, favoriteColor: 'blue' },
    { name: 'Ivan', age: 35, favoriteColor: 'green' },
    { name: 'Judy', age: 24, favoriteColor: 'red' },
    { name: 'Mallory', age: 32, favoriteColor: 'orange' },
    { name: 'Nina', age: 27, favoriteColor: 'blue' },
    { name: 'Oscar', age: 36, favoriteColor: 'green' },
    { name: 'Peggy', age: 23, favoriteColor: 'red' },
    { name: 'Trent', age: 33, favoriteColor: 'orange' },
    { name: 'Victor', age: 37, favoriteColor: 'blue' },
    { name: 'Walter', age: 39, favoriteColor: 'green' },
    { name: 'Xena', age: 29, favoriteColor: 'red' },
    { name: 'Yolanda', age: 31, favoriteColor: 'orange' },
    { name: 'Zane', age: 30, favoriteColor: 'blue' },
    { name: 'Alex', age: 25, favoriteColor: 'green' },
    { name: 'Bella', age: 28, favoriteColor: 'red' },
    { name: 'Cindy', age: 34, favoriteColor: 'orange' },
    { name: 'Derek', age: 26, favoriteColor: 'blue' },
    { name: 'Ethan', age: 32, favoriteColor: 'green' },
    { name: 'Faith', age: 22, favoriteColor: 'red' },
    { name: 'George', age: 27, favoriteColor: 'orange' },
    { name: 'Hannah', age: 35, favoriteColor: 'blue' },
    { name: 'Isla', age: 24, favoriteColor: 'green' },
    { name: 'Jack', age: 40, favoriteColor: 'red' },
    { name: 'Kara', age: 29, favoriteColor: 'orange' },
    { name: 'Liam', age: 33, favoriteColor: 'blue' },
    { name: 'Mona', age: 31, favoriteColor: 'green' },
    { name: 'Nate', age: 28, favoriteColor: 'red' },
    { name: 'Olivia', age: 36, favoriteColor: 'orange' },
    { name: 'Paul', age: 23, favoriteColor: 'blue' },
    { name: 'Quinn', age: 34, favoriteColor: 'green' },
    { name: 'Rachel', age: 26, favoriteColor: 'red' },
    { name: 'Steve', age: 30, favoriteColor: 'orange' },
    { name: 'Tina', age: 39, favoriteColor: 'blue' },
    { name: 'Uma', age: 32, favoriteColor: 'green' },
    { name: 'Vera', age: 27, favoriteColor: 'red' },
    { name: 'Wayne', age: 25, favoriteColor: 'orange' },
    { name: 'Xander', age: 35, favoriteColor: 'blue' },
    { name: 'Yara', age: 28, favoriteColor: 'green' },
    { name: 'Zoe', age: 24, favoriteColor: 'red' },
    { name: 'Adam', age: 31, favoriteColor: 'orange' },
    { name: 'Bianca', age: 29, favoriteColor: 'blue' },
    { name: 'Chad', age: 36, favoriteColor: 'green' },
    { name: 'Daisy', age: 22, favoriteColor: 'red' },
    { name: 'Eli', age: 33, favoriteColor: 'orange' },
    { name: 'Fiona', age: 30, favoriteColor: 'blue' },
    { name: 'Gabe', age: 34, favoriteColor: 'green' },
    { name: 'Hazel', age: 27, favoriteColor: 'red' },
    { name: 'Ivy', age: 28, favoriteColor: 'orange' },
    { name: 'Jon', age: 37, favoriteColor: 'blue' },
    { name: 'Kayla', age: 25, favoriteColor: 'green' },
    { name: 'Leo', age: 29, favoriteColor: 'red' },
    { name: 'Mia', age: 32, favoriteColor: 'orange' },
    { name: 'Nick', age: 39, favoriteColor: 'blue' },
    { name: 'Olga', age: 24, favoriteColor: 'green' },
    { name: 'Pete', age: 31, favoriteColor: 'red' },
    { name: 'Quincy', age: 23, favoriteColor: 'orange' },
    { name: 'Rose', age: 26, favoriteColor: 'blue' },
    { name: 'Scott', age: 34, favoriteColor: 'green' },
    { name: 'Tara', age: 36, favoriteColor: 'red' },
    { name: 'Umar', age: 27, favoriteColor: 'orange' },
    { name: 'Val', age: 30, favoriteColor: 'blue' },
    { name: 'Will', age: 28, favoriteColor: 'green' },
    { name: 'Ximena', age: 25, favoriteColor: 'red' },
    { name: 'Yasmin', age: 33, favoriteColor: 'orange' },
    { name: 'Zack', age: 40, favoriteColor: 'blue' },
    { name: 'Amber', age: 29, favoriteColor: 'green' },
    { name: 'Ben', age: 24, favoriteColor: 'red' },
    { name: 'Cara', age: 37, favoriteColor: 'orange' },
    { name: 'Dion', age: 31, favoriteColor: 'blue' },
    { name: 'Elise', age: 32, favoriteColor: 'green' },
    { name: 'Felix', age: 26, favoriteColor: 'red' },
    { name: 'Gwen', age: 35, favoriteColor: 'orange' },
    { name: 'Hugo', age: 23, favoriteColor: 'blue' },
    { name: 'Iris', age: 39, favoriteColor: 'green' },
    { name: 'Jamie', age: 27, favoriteColor: 'red' },
    { name: 'Ken', age: 36, favoriteColor: 'orange' },
    { name: 'Lara', age: 25, favoriteColor: 'blue' },
    { name: 'Max', age: 33, favoriteColor: 'green' },
    { name: 'Nora', age: 30, favoriteColor: 'red' },
    { name: 'Owen', age: 29, favoriteColor: 'orange' },
    { name: 'Paula', age: 34, favoriteColor: 'blue' },
    { name: 'Rex', age: 28, favoriteColor: 'green' },
    { name: 'Sue', age: 22, favoriteColor: 'red' },
    { name: 'Tom', age: 31, favoriteColor: 'orange' },
    { name: 'Uma', age: 37, favoriteColor: 'blue' },
    { name: 'Vince', age: 35, favoriteColor: 'green' },
    { name: 'Wendy', age: 24, favoriteColor: 'red' },
    { name: 'Xia', age: 40, favoriteColor: 'orange' },
    { name: 'Yanni', age: 27, favoriteColor: 'blue' },
    { name: 'Zara', age: 26, favoriteColor: 'green' }
];

const currentUsers: User[] = [];
const processingState: ProcessingState = {
    sort: null,
    filter: null,
    pagination: {currentPage: 0, itemsPerPage: 10},
    search: null,
};

/* Default state of the application */
export const defaultState = {
    users,
    currentUsers,
    processingState
};

export type AppState = typeof defaultState;
